export const COUNTRY_ISO3_CODES = [
  'AFG',
  'ALA',
  'ALB',
  'DZA',
  'AND',
  'AGO',
  'AIA',
  'ATG',
  'ARE',
  'ARG',
  'ARM',
  'ABW',
  'AUS',
  'AUT',
  'AZE',
  'BHS',
  'BHR',
  'BGD',
  'BRB',
  'BLR',
  'BEL',
  'BLZ',
  'BEN',
  'BMU',
  'BTN',
  'BOL',
  'BIH',
  'BWA',
  'BRA',
  'VGB',
  'BRN',
  'BGR',
  'BFA',
  'BDI',
  'CPV',
  'KHM',
  'CMR',
  'CAN',
  'CYM',
  'CAF',
  'TCD',
  'CHL',
  'CHN',
  'COL',
  'COM',
  'COD',
  'COG',
  'CRI',
  'CIV',
  'HRV',
  'CUB',
  'CYP',
  'CZE',
  'DNK',
  'DJI',
  'DMA',
  'DOM',
  'ECU',
  'EGY',
  'SLV',
  'GNQ',
  'ERI',
  'EST',
  'ETH',
  'FLK',
  'FJI',
  'FIN',
  'FRA',
  'GAB',
  'GMB',
  'GEO',
  'DEU',
  'GHA',
  'GIB',
  'GBR',
  'GRC',
  'GRD',
  'GTM',
  'GGY',
  'GIN',
  'GNB',
  'GUY',
  'HTI',
  'HND',
  'HKG',
  'HUN',
  'ISL',
  'IND',
  'IDN',
  'IRN',
  'IRQ',
  'IRL',
  'IMN',
  'ISR',
  'ITA',
  'JAM',
  'JPN',
  'JEY',
  'JOR',
  'KAZ',
  'KEN',
  'PRK',
  'KOR',
  'KWT',
  'KGZ',
  'LAO',
  'LVA',
  'LBN',
  'LSO',
  'LBR',
  'LBY',
  'LIE',
  'LTU',
  'LUX',
  'MAC',
  'MKD',
  'MDG',
  'MWI',
  'MYS',
  'MDV',
  'MLI',
  'MLT',
  'MRT',
  'MUS',
  'MEX',
  'FSM',
  'MDA',
  'MCO',
  'MNG',
  'MNE',
  'MSR',
  'MAR',
  'MOZ',
  'MMR',
  'NAM',
  'NPL',
  'NLD',
  'ANT',
  'NZL',
  'NIC',
  'NER',
  'NGA',
  'NOR',
  'OMN',
  'PAK',
  'PLW',
  'PAN',
  'PNG',
  'PRY',
  'PER',
  'PHL',
  'POL',
  'PYF',
  'PRT',
  'PRI',
  'QAT',
  'ROU',
  'RUS',
  'RWA',
  'SHN',
  'KNA',
  'LCA',
  'VCT',
  'WSM',
  'SMR',
  'STP',
  'SAU',
  'SEN',
  'SRB',
  'SYC',
  'SLE',
  'SGP',
  'SVK',
  'SVN',
  'SLB',
  'SOM',
  'ZAF',
  'ESP',
  'LKA',
  'SDN',
  'SUR',
  'SWZ',
  'SWE',
  'CHE',
  'SYR',
  'TWN',
  'TJK',
  'TZA',
  'THA',
  'TLS',
  'TGO',
  'TON',
  'TTO',
  'TUN',
  'TUR',
  'TKM',
  'TCA',
  'UGA',
  'UKR',
  'USA',
  'URY',
  'UZB',
  'VUT',
  'VEN',
  'VNM',
  'YEM',
  'ZMB',
  'ZWE',
];
const COUNTRY_NAMES = [
  'Afghanistan',
  'AlandIslands',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'AntiguaAndBarbuda',
  'ArabEmirates',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'BosniaAndHerzegovina',
  'Botswana',
  'Brazil',
  'BritishVirginIslands',
  'Brunei',
  'Bulgaria',
  'BurkinaFaso',
  'Burundi',
  'CaboVerde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'CaymanIslands',
  'CentralAfricanRepublic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'CongoDemocraticRepublic',
  'CongoRepublic',
  'CostaRica',
  'CoteDIvoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'DominicanRepublic',
  'Ecuador',
  'Egypt',
  'ElSalvador',
  'EquatorialGuinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'FalklandIslands',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'GreatBritain',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'GuineaBissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'HongKong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'IsleOfMan',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'KoreaNorth',
  'KoreaSouth',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'NetherlandsAntillesCountry',
  'NewZealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'PapuaNewGuinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'PolynesiaFrench',
  'Portugal',
  'PuertoRico',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'SaintHelena',
  'SaintKittsAndNevis',
  'SaintLucia',
  'SaintVincentAndTheGrenadines',
  'Samoa',
  'SanMarino',
  'SaoTomeAndPrincipe',
  'SaudiArabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'SierraLeone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'SolomonIslands',
  'Somalia',
  'SouthAfrica',
  'Spain',
  'SriLanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'TimorLeste',
  'Togo',
  'Tonga',
  'TrinidadAndTobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'TurksAndCaicosIslands',
  'Uganda',
  'Ukraine',
  'UnitedStatesOfAmerica',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const;

export type CountryName = typeof COUNTRY_NAMES[number];
export type CountryIso3Code = typeof COUNTRY_ISO3_CODES[number];

export const CountryNames: { [key in CountryIso3Code]: CountryName } = {
  AFG: 'Afghanistan',
  ALA: 'AlandIslands',
  ALB: 'Albania',
  DZA: 'Algeria',
  AND: 'Andorra',
  AGO: 'Angola',
  AIA: 'Anguilla',
  ATG: 'AntiguaAndBarbuda',
  ARE: 'ArabEmirates',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ABW: 'Aruba',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BHS: 'Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BLZ: 'Belize',
  BEN: 'Benin',
  BMU: 'Bermuda',
  BTN: 'Bhutan',
  BOL: 'Bolivia',
  BIH: 'BosniaAndHerzegovina',
  BWA: 'Botswana',
  BRA: 'Brazil',
  VGB: 'BritishVirginIslands',
  BRN: 'Brunei',
  BGR: 'Bulgaria',
  BFA: 'BurkinaFaso',
  BDI: 'Burundi',
  CPV: 'CaboVerde',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CYM: 'CaymanIslands',
  CAF: 'CentralAfricanRepublic',
  TCD: 'Chad',
  CHL: 'Chile',
  CHN: 'China',
  COL: 'Colombia',
  COM: 'Comoros',
  COD: 'CongoDemocraticRepublic',
  COG: 'CongoRepublic',
  CRI: 'CostaRica',
  CIV: 'CoteDIvoire',
  HRV: 'Croatia',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DNK: 'Denmark',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  DOM: 'DominicanRepublic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  SLV: 'ElSalvador',
  GNQ: 'EquatorialGuinea',
  ERI: 'Eritrea',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FLK: 'FalklandIslands',
  FJI: 'Fiji',
  FIN: 'Finland',
  FRA: 'France',
  GAB: 'Gabon',
  GMB: 'Gambia',
  GEO: 'Georgia',
  DEU: 'Germany',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GBR: 'GreatBritain',
  GRC: 'Greece',
  GRD: 'Grenada',
  GTM: 'Guatemala',
  GGY: 'Guernsey',
  GIN: 'Guinea',
  GNB: 'GuineaBissau',
  GUY: 'Guyana',
  HTI: 'Haiti',
  HND: 'Honduras',
  HKG: 'HongKong',
  HUN: 'Hungary',
  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  IMN: 'IsleOfMan',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JPN: 'Japan',
  JEY: 'Jersey',
  JOR: 'Jordan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  PRK: 'KoreaNorth',
  KOR: 'KoreaSouth',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',
  LAO: 'Laos',
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LSO: 'Lesotho',
  LBR: 'Liberia',
  LBY: 'Libya',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MAC: 'Macao',
  MKD: 'Macedonia',
  MDG: 'Madagascar',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malta',
  MRT: 'Mauritania',
  MUS: 'Mauritius',
  MEX: 'Mexico',
  FSM: 'Micronesia',
  MDA: 'Moldova',
  MCO: 'Monaco',
  MNG: 'Mongolia',
  MNE: 'Montenegro',
  MSR: 'Montserrat',
  MAR: 'Morocco',
  MOZ: 'Mozambique',
  MMR: 'Myanmar',
  NAM: 'Namibia',
  NPL: 'Nepal',
  NLD: 'Netherlands',
  ANT: 'NetherlandsAntillesCountry',
  NZL: 'NewZealand',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  NOR: 'Norway',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PLW: 'Palau',
  PAN: 'Panama',
  PNG: 'PapuaNewGuinea',
  PRY: 'Paraguay',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PYF: 'PolynesiaFrench',
  PRT: 'Portugal',
  PRI: 'PuertoRico',
  QAT: 'Qatar',
  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',
  SHN: 'SaintHelena',
  KNA: 'SaintKittsAndNevis',
  LCA: 'SaintLucia',
  VCT: 'SaintVincentAndTheGrenadines',
  WSM: 'Samoa',
  SMR: 'SanMarino',
  STP: 'SaoTomeAndPrincipe',
  SAU: 'SaudiArabia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SYC: 'Seychelles',
  SLE: 'SierraLeone',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SLB: 'SolomonIslands',
  SOM: 'Somalia',
  ZAF: 'SouthAfrica',
  ESP: 'Spain',
  LKA: 'SriLanka',
  SDN: 'Sudan',
  SUR: 'Suriname',
  SWZ: 'Swaziland',
  SWE: 'Sweden',
  CHE: 'Switzerland',
  SYR: 'Syria',
  TWN: 'Taiwan',
  TJK: 'Tajikistan',
  TZA: 'Tanzania',
  THA: 'Thailand',
  TLS: 'TimorLeste',
  TGO: 'Togo',
  TON: 'Tonga',
  TTO: 'TrinidadAndTobago',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TKM: 'Turkmenistan',
  TCA: 'TurksAndCaicosIslands',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  USA: 'UnitedStatesOfAmerica',
  URY: 'Uruguay',
  UZB: 'Uzbekistan',
  VUT: 'Vanuatu',
  VEN: 'Venezuela',
  VNM: 'Vietnam',
  YEM: 'Yemen',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
};

export const CountryRusNames: { [key in CountryIso3Code]: string } = {
  AFG: 'Афганистан',
  ALA: 'Аландские острова',
  ALB: 'Албания',
  DZA: 'Алжир',
  AND: 'Андорра',
  AGO: 'Ангола',
  AIA: 'Ангилья',
  ATG: 'Антигуа и Барбуда',
  ARE: 'Объединенные Арабские Эмираты',
  ARG: 'Аргентина',
  ARM: 'Армения',
  ABW: 'Аруба',
  AUS: 'Австралия',
  AUT: 'Австрия',
  AZE: 'Азербайджан',
  BHS: 'Багамские острова',
  BHR: 'Бахрейн',
  BGD: 'Бангладеш',
  BRB: 'Барбадос',
  BLR: 'Белоруссия',
  BEL: 'Бельгия',
  BLZ: 'Белиз',
  BEN: 'Бенин',
  BMU: 'Бермудские острова',
  BTN: 'Бутан',
  BOL: 'Боливия',
  BIH: 'Босния и Герцеговина',
  BWA: 'Ботсвана',
  BRA: 'Бразилия',
  VGB: 'Британские Виргинские Острова',
  BRN: 'Бруней',
  BGR: 'Болгария',
  BFA: 'Буркина-Фасо',
  BDI: 'Бурунди',
  CPV: 'Кабо-Верде',
  KHM: 'Камбоджа',
  CMR: 'Камерун',
  CAN: 'Канада',
  CYM: 'Каймановы острова',
  CAF: 'Центральноафриканская Республика',
  TCD: 'Чад',
  CHL: 'Чили',
  CHN: 'Китай',
  COL: 'Колумбия',
  COM: 'Коморы',
  COD: 'Демократическая Республика Конго',
  COG: 'Конго',
  CRI: 'Коста-Рика',
  CIV: "Кот-д'Ивуар",
  HRV: 'Хорватия',
  CUB: 'Куба',
  CYP: 'Кипр',
  CZE: 'Чехия',
  DNK: 'Дания',
  DJI: 'Джибути',
  DMA: 'Доминика',
  DOM: 'Доминиканская Республика',
  ECU: 'Эквадор',
  EGY: 'Египет',
  SLV: 'Сальвадор',
  GNQ: 'Экваториальная Гвинея',
  ERI: 'Эритрея',
  EST: 'Эстония',
  ETH: 'Эфиопия',
  FLK: 'Фолклендские острова',
  FJI: 'Фиджи',
  FIN: 'Финляндия',
  FRA: 'Франция',
  GAB: 'Габон',
  GMB: 'Гамбия',
  GEO: 'Грузия',
  DEU: 'Германия',
  GHA: 'Гана',
  GIB: 'Гибралтар',
  GBR: 'Великобритания',
  GRC: 'Греция',
  GRD: 'Гренада',
  GTM: 'Гватемала',
  GGY: 'Гернси',
  GIN: 'Гвинея',
  GNB: 'Гвинея-Бисау',
  GUY: 'Гайана',
  HTI: 'Гаити',
  HND: 'Гондурас',
  HKG: 'Гонконг',
  HUN: 'Венгрия',
  ISL: 'Исландия',
  IND: 'Индия',
  IDN: 'Индонезия',
  IRN: 'Иран',
  IRQ: 'Ирак',
  IRL: 'Ирландия',
  IMN: 'Остров Мэн',
  ISR: 'Израиль',
  ITA: 'Италия',
  JAM: 'Ямайка',
  JPN: 'Япония',
  JEY: 'Джерси',
  JOR: 'Иордания',
  KAZ: 'Казахстан',
  KEN: 'Кения',
  PRK: 'Северная Корея',
  KOR: 'Южная Корея',
  KWT: 'Кувейт',
  KGZ: 'Киргизия',
  LAO: 'Лаос',
  LVA: 'Латвия',
  LBN: 'Ливан',
  LSO: 'Лесото',
  LBR: 'Либерия',
  LBY: 'Ливия',
  LIE: 'Лихтенштейн',
  LTU: 'Литва',
  LUX: 'Люксембург',
  MAC: 'Макао',
  MKD: 'Северная Македония',
  MDG: 'Мадагаскар',
  MWI: 'Малави',
  MYS: 'Малайзия',
  MDV: 'Мальдивы',
  MLI: 'Мали',
  MLT: 'Мальта',
  MRT: 'Мавритания',
  MUS: 'Маврикий',
  MEX: 'Мексика',
  FSM: 'Микронезия',
  MDA: 'Молдавия',
  MCO: 'Монако',
  MNG: 'Монголия',
  MNE: 'Черногория',
  MSR: 'Монтсеррат',
  MAR: 'Марокко',
  MOZ: 'Мозамбик',
  MMR: 'Мьянма',
  NAM: 'Намибия',
  NPL: 'Непал',
  NLD: 'Нидерланды',
  ANT: 'Нидерландские Антильские острова',
  NZL: 'Новая Зеландия',
  NIC: 'Никарагуа',
  NER: 'Нигер',
  NGA: 'Нигерия',
  NOR: 'Норвегия',
  OMN: 'Оман',
  PAK: 'Пакистан',
  PLW: 'Палау',
  PAN: 'Панама',
  PNG: 'Папуа-Новая Гвинея',
  PRY: 'Парагвай',
  PER: 'Перу',
  PHL: 'Филиппины',
  POL: 'Польша',
  PYF: 'Французская Полинезия',
  PRT: 'Португалия',
  PRI: 'Пуэрто-Рико',
  QAT: 'Катар',
  ROU: 'Румыния',
  RUS: 'Россия',
  RWA: 'Руанда',
  SHN: 'Остров Святой Елены',
  KNA: 'Сент-Китс и Невис',
  LCA: 'Сент-Люсия',
  VCT: 'Сент-Винсент и Гренадины',
  WSM: 'Самоа',
  SMR: 'Сан-Марино',
  STP: 'Сан-Томе и Принсипи',
  SAU: 'Саудовская Аравия',
  SEN: 'Сенегал',
  SRB: 'Сербия',
  SYC: 'Сейшелы',
  SLE: 'Сьерра-Леоне',
  SGP: 'Сингапур',
  SVK: 'Словакия',
  SVN: 'Словения',
  SLB: 'Соломоновы острова',
  SOM: 'Сомали',
  ZAF: 'Южная Африка',
  ESP: 'Испания',
  LKA: 'Шри-Ланка',
  SDN: 'Судан',
  SUR: 'Суринам',
  SWZ: 'Эсватини',
  SWE: 'Швеция',
  CHE: 'Швейцария',
  SYR: 'Сирия',
  TWN: 'Тайвань',
  TJK: 'Таджикистан',
  TZA: 'Танзания',
  THA: 'Таиланд',
  TLS: 'Восточный Тимор',
  TGO: 'Того',
  TON: 'Тонга',
  TTO: 'Тринидад и Тобаго',
  TUN: 'Тунис',
  TUR: 'Турция',
  TKM: 'Туркменистан',
  TCA: 'Острова Теркс и Кайкос',
  UGA: 'Уганда',
  UKR: 'Украина',
  USA: 'Соединенные Штаты Америки',
  URY: 'Уругвай',
  UZB: 'Узбекистан',
  VUT: 'Вануату',
  VEN: 'Венесуэла',
  VNM: 'Вьетнам',
  YEM: 'Йемен',
  ZMB: 'Замбия',
  ZWE: 'Зимбабве',
};

export const CountryCodes: { [key in CountryIso3Code]: Array<string> } = {
  AFG: ['+93'],
  ALA: ['+358'],
  ALB: ['+355'],
  DZA: ['+213'],
  AND: ['+376'],
  AGO: ['+244'],
  AIA: ['+1-264'],
  ATG: ['+1-268'],
  ARE: ['+971'],
  ARG: ['+54'],
  ARM: ['+374'],
  ABW: ['+297'],
  AUS: ['+61'],
  AUT: ['+43'],
  AZE: ['+994'],
  BHS: ['+1-242'],
  BHR: ['+973'],
  BGD: ['+880'],
  BRB: ['+1-246'],
  BLR: ['+375'],
  BEL: ['+32'],
  BLZ: ['+501'],
  BEN: ['+229'],
  BMU: ['+1-441'],
  BTN: ['+975'],
  BOL: ['+591'],
  BIH: ['+387'],
  BWA: ['+267'],
  BRA: ['+55'],
  VGB: ['+1-284'],
  BRN: ['+673'],
  BGR: ['+359'],
  BFA: ['+226'],
  BDI: ['+257'],
  CPV: ['+238'],
  KHM: ['+855'],
  CMR: ['+237'],
  CAN: ['+1'],
  CYM: ['+1-345'],
  CAF: ['+236'],
  TCD: ['+235'],
  CHL: ['+56'],
  CHN: ['+86'],
  COL: ['+57'],
  COM: ['+269'],
  COD: ['+243'],
  COG: ['+242'],
  CRI: ['+506'],
  CIV: ['+225'],
  HRV: ['+385'],
  CUB: ['+53'],
  CYP: ['+357'],
  CZE: ['+420'],
  DNK: ['+45'],
  DJI: ['+253'],
  DMA: ['+1-767'],
  DOM: ['+1-809', '+1-829', '+1-849'],
  ECU: ['+593'],
  EGY: ['+20'],
  SLV: ['+503'],
  GNQ: ['+240'],
  ERI: ['+291'],
  EST: ['+372'],
  ETH: ['+251'],
  FLK: ['+500'],
  FJI: ['+679'],
  FIN: ['+358'],
  FRA: ['+33'],
  GAB: ['+241'],
  GMB: ['+220'],
  GEO: ['+995'],
  DEU: ['+49'],
  GHA: ['+233'],
  GIB: ['+350'],
  GBR: ['+44'],
  GRC: ['+30'],
  GRD: ['+1-473'],
  GTM: ['+502'],
  GGY: ['+44-1481'],
  GIN: ['+224'],
  GNB: ['+245'],
  GUY: ['+592'],
  HTI: ['+509'],
  HND: ['+504'],
  HKG: ['+852'],
  HUN: ['+36'],
  ISL: ['+354'],
  IND: ['+91'],
  IDN: ['+62'],
  IRN: ['+98'],
  IRQ: ['+964'],
  IRL: ['+353'],
  IMN: ['+44-1624'],
  ISR: ['+972'],
  ITA: ['+39'],
  JAM: ['+1-876'],
  JPN: ['+81'],
  JEY: ['+44-1534'],
  JOR: ['+962'],
  KAZ: ['+7'],
  KEN: ['+254'],
  PRK: ['+850'],
  KOR: ['+82'],
  KWT: ['+965'],
  KGZ: ['+996'],
  LAO: ['+856'],
  LVA: ['+371'],
  LBN: ['+961'],
  LSO: ['+266'],
  LBR: ['+231'],
  LBY: ['+218'],
  LIE: ['+423'],
  LTU: ['+370'],
  LUX: ['+352'],
  MAC: ['+853'],
  MKD: ['+389'],
  MDG: ['+261'],
  MWI: ['+265'],
  MYS: ['+213'],
  MDV: ['+960'],
  MLI: ['+223'],
  MLT: ['+356'],
  MRT: ['+222'],
  MUS: ['+230'],
  MEX: ['+52'],
  FSM: ['+691'],
  MDA: ['+373'],
  MCO: ['+377'],
  MNG: ['+976'],
  MNE: ['+382'],
  MSR: ['+1-664'],
  MAR: ['+212'],
  MOZ: ['+258'],
  MMR: ['+95'],
  NAM: ['+264'],
  NPL: ['+977'],
  NLD: ['+31'],
  ANT: ['+599'],
  NZL: ['+64'],
  NIC: ['+505'],
  NER: ['+227'],
  NGA: ['+234'],
  NOR: ['+47'],
  OMN: ['+968'],
  PAK: ['+92'],
  PLW: ['+680'],
  PAN: ['+507'],
  PNG: ['+675'],
  PRY: ['+595'],
  PER: ['+51'],
  PHL: ['+63'],
  POL: ['+48'],
  PYF: ['+689'],
  PRT: ['+351'],
  PRI: ['+1-787', '+1-939'],
  QAT: ['+974'],
  ROU: ['+40'],
  RUS: ['+7'],
  RWA: ['+250'],
  SHN: ['+290'],
  KNA: ['+1-869'],
  LCA: ['+1-758'],
  VCT: ['+1-784'],
  WSM: ['+685'],
  SMR: ['+378'],
  STP: ['+239'],
  SAU: ['+966'],
  SEN: ['+221'],
  SRB: ['+381'],
  SYC: ['+248'],
  SLE: ['+232'],
  SGP: ['+65'],
  SVK: ['+421'],
  SVN: ['+386'],
  SLB: ['+677'],
  SOM: ['+252'],
  ZAF: ['+27'],
  ESP: ['+34'],
  LKA: ['+94'],
  SDN: ['+249'],
  SUR: ['+597'],
  SWZ: ['+213'],
  SWE: ['+46'],
  CHE: ['+41'],
  SYR: ['+963'],
  TWN: ['+886'],
  TJK: ['+992'],
  TZA: ['+255'],
  THA: ['+66'],
  TLS: ['+670'],
  TGO: ['+228'],
  TON: ['+676'],
  TTO: ['+1-868'],
  TUN: ['+216'],
  TUR: ['+90'],
  TKM: ['+993'],
  TCA: ['+1-649'],
  UGA: ['+256'],
  UKR: ['+380'],
  USA: ['+1'],
  URY: ['+598'],
  UZB: ['+998'],
  VUT: ['+678'],
  VEN: ['+58'],
  VNM: ['+84'],
  YEM: ['+967'],
  ZMB: ['+260'],
  ZWE: ['+263'],
};

export const PhoneCodes: { [key: string]: Array<CountryIso3Code> } = {
  '1': ['CAN', 'USA'],
  '7': ['KAZ', 'RUS'],
  '20': ['EGY'],
  '27': ['ZAF'],
  '30': ['GRC'],
  '31': ['NLD'],
  '32': ['BEL'],
  '33': ['FRA'],
  '34': ['ESP'],
  '36': ['HUN'],
  '39': ['ITA'],
  '40': ['ROU'],
  '41': ['CHE'],
  '43': ['AUT'],
  '44': ['GBR'],
  '45': ['DNK'],
  '46': ['SWE'],
  '47': ['NOR'],
  '48': ['POL'],
  '49': ['DEU'],
  '51': ['PER'],
  '52': ['MEX'],
  '53': ['CUB'],
  '54': ['ARG'],
  '55': ['BRA'],
  '56': ['CHL'],
  '57': ['COL'],
  '58': ['VEN'],
  '60': ['MYS'],
  '61': ['AUS'],
  '62': ['IDN'],
  '63': ['PHL'],
  '64': ['NZL'],
  '65': ['SGP'],
  '66': ['THA'],
  '81': ['JPN'],
  '82': ['KOR'],
  '84': ['VNM'],
  '86': ['CHN'],
  '90': ['TUR'],
  '91': ['IND'],
  '92': ['PAK'],
  '93': ['AFG'],
  '94': ['LKA'],
  '95': ['MMR'],
  '98': ['IRN'],
  '212': ['MAR'],
  '213': ['DZA'],
  '216': ['TUN'],
  '218': ['LBY'],
  '220': ['GMB'],
  '221': ['SEN'],
  '222': ['MRT'],
  '223': ['MLI'],
  '224': ['GIN'],
  '225': ['CIV'],
  '226': ['BFA'],
  '227': ['NER'],
  '228': ['TGO'],
  '229': ['BEN'],
  '230': ['MUS'],
  '231': ['LBR'],
  '232': ['SLE'],
  '233': ['GHA'],
  '234': ['NGA'],
  '235': ['TCD'],
  '236': ['CAF'],
  '237': ['CMR'],
  '238': ['CPV'],
  '239': ['STP'],
  '240': ['GNQ'],
  '241': ['GAB'],
  '242': ['COG'],
  '243': ['COD'],
  '244': ['AGO'],
  '245': ['GNB'],
  '248': ['SYC'],
  '249': ['SDN'],
  '250': ['RWA'],
  '251': ['ETH'],
  '252': ['SOM'],
  '253': ['DJI'],
  '254': ['KEN'],
  '255': ['TZA'],
  '256': ['UGA'],
  '257': ['BDI'],
  '258': ['MOZ'],
  '260': ['ZMB'],
  '261': ['MDG'],
  '263': ['ZWE'],
  '264': ['NAM'],
  '265': ['MWI'],
  '266': ['LSO'],
  '267': ['BWA'],
  '268': ['SWZ'],
  '269': ['COM'],
  '290': ['SHN'],
  '291': ['ERI'],
  '297': ['ABW'],
  '350': ['GIB'],
  '351': ['PRT'],
  '352': ['LUX'],
  '353': ['IRL'],
  '354': ['ISL'],
  '355': ['ALB'],
  '356': ['MLT'],
  '357': ['CYP'],
  '358': ['ALA', 'FIN'],
  '359': ['BGR'],
  '370': ['LTU'],
  '371': ['LVA'],
  '372': ['EST'],
  '373': ['MDA'],
  '374': ['ARM'],
  '375': ['BLR'],
  '376': ['AND'],
  '377': ['MCO'],
  '378': ['SMR'],
  '380': ['UKR'],
  '381': ['SRB'],
  '382': ['MNE'],
  '385': ['HRV'],
  '386': ['SVN'],
  '387': ['BIH'],
  '389': ['MKD'],
  '420': ['CZE'],
  '421': ['SVK'],
  '423': ['LIE'],
  '500': ['FLK'],
  '501': ['BLZ'],
  '502': ['GTM'],
  '503': ['SLV'],
  '504': ['HND'],
  '505': ['NIC'],
  '506': ['CRI'],
  '507': ['PAN'],
  '509': ['HTI'],
  '591': ['BOL'],
  '592': ['GUY'],
  '593': ['ECU'],
  '595': ['PRY'],
  '597': ['SUR'],
  '598': ['URY'],
  '599': ['ANT'],
  '670': ['TLS'],
  '673': ['BRN'],
  '675': ['PNG'],
  '676': ['TON'],
  '677': ['SLB'],
  '678': ['VUT'],
  '679': ['FJI'],
  '680': ['PLW'],
  '685': ['WSM'],
  '689': ['PYF'],
  '691': ['FSM'],
  '850': ['PRK'],
  '852': ['HKG'],
  '853': ['MAC'],
  '855': ['KHM'],
  '856': ['LAO'],
  '880': ['BGD'],
  '886': ['TWN'],
  '960': ['MDV'],
  '961': ['LBN'],
  '962': ['JOR'],
  '963': ['SYR'],
  '964': ['IRQ'],
  '965': ['KWT'],
  '966': ['SAU'],
  '967': ['YEM'],
  '968': ['OMN'],
  '971': ['ARE'],
  '972': ['ISR'],
  '973': ['BHR'],
  '974': ['QAT'],
  '975': ['BTN'],
  '976': ['MNG'],
  '977': ['NPL'],
  '992': ['TJK'],
  '993': ['TKM'],
  '994': ['AZE'],
  '995': ['GEO'],
  '996': ['KGZ'],
  '998': ['UZB'],
  '1242': ['BHS'],
  '1246': ['BRB'],
  '1264': ['AIA'],
  '1268': ['ATG'],
  '1284': ['VGB'],
  '1345': ['CYM'],
  '1441': ['BMU'],
  '1473': ['GRD'],
  '1649': ['TCA'],
  '1664': ['MSR'],
  '1758': ['LCA'],
  '1767': ['DMA'],
  '1784': ['VCT'],
  '1787': ['PRI'],
  '1809': ['DOM'],
  '1829': ['DOM'],
  '1849': ['DOM'],
  '1868': ['TTO'],
  '1869': ['KNA'],
  '1876': ['JAM'],
  '1939': ['PRI'],
  '441481': ['GGY'],
  '441534': ['JEY'],
  '441624': ['IMN'],
};
