# Dockerfile.storybook
FROM node:22-alpine

WORKDIR /app

# COPY package.docker.platwright.json ./package.json
COPY docker/package.storybook.json ./package.json

# Переименовываем
# RUN mv package.storybook.json 

RUN npm i

COPY .storybook/ ./.storybook/
COPY src/ ./src/
COPY tsconfig.json ./

EXPOSE 6006

CMD ["npm", "run", "storybook"]