import type { Background, Basic, Color, Special, SpecialInvert, Status, Text } from '../common';

const BASIC: Basic = {
  primary: '#0D69F2',
  secondary: '#2B313B',
  tertiary: '#8A96A8',
  hover: '#0A54C2',
  press: '#0949AA',
  disable: '#C4CAD4',
  primaryLight: '#6EA5F7',
} as const;

const BACKGROUND: Background = {
  primary: '#FFFFFF',
  secondary: '#F1F2F4',
  tertiary: '#E2E5E9',
  tertiaryHover: '#D3D8DE',
  card: '#FFFFFF',
  cardHover: '#FFFFFF',
  inversion: '#2B313B',
  shadow: '#8A96A8',
  header: '#0949AA',
  surfaceDanger: '#FEF0F1',
  surfaceWarn: '#FFF7F0',
  surfaceSuccess: '#F2FCF5',
  page: '#F1F2F4',
} as const;

const TEXT: Text = {
  primary: '#2B313B',
  secondary: '#626F84',
  tertiary: '#A7B0BE',
  inversion: '#FFFFFF',
  staticWhite: '#FFFFFF',
  staticBlack: '#2B313B',
} as const;

const STATUS: Status = {
  warn: '#FF8C19',
  hoverWarn: '#E57300',
  pressWarn: '#CC6600',
  success: '#2ABB5B',
  hoverSuccess: '#219246',
  pressSuccess: '#1C7D3C',
  danger: '#DA0B20',
  hoverDanger: '#A90919',
  pressDanger: '#910815',
} as const;

const SPECIAL: Special = {
  blueLight: '#0ABBFB',
  lightBlue: '#0ABBFB',
  blue: '#3F7DFE',
  blueDeep: '#3E51B5',
  greenLight: '#C0D20F',
  green: '#5ECF70',
  greenDeep: '#44BF78',
  tiffany: '#5BD8D1',
  tiffanyDeep: '#24A79F',
  tiffanyDark: '#147F94',
  tiffanyBlue: '#00BCD4',
  yellow: '#F0DE37',
  orangeLight: '#FFAF37',
  orange: '#FF8515',
  orangeDeep: '#FF5A32',
  violetLight: '#ED6CCD',
  violet: '#C368DA',
  violetDeep: '#9A64F7',
  fuchsia: '#F86D86',
  fuchsiaDeep: '#D9477C',
  rainySky: '#62676F',
  night: '#2B313B',
  gray: '#98ABCD',
  softBlue: '#E0F2FF',
  softNiceBlue: '#E0E9FF',
  softSkyBlue: '#E2F4FE',
  softTiffany: '#DBF8FF',
  softGreen: '#D8F5E8',
  softYellow: '#FFF1D4',
  softPapaya: '#F9EECF',
  softRed: '#FFEBED',
  softPink: '#FFEBF8',
  softPurple: '#EDF1FF',
  softMallowPurple: '#E8E6FF',
  softGray: '#F1F2F4',
  softLightBlue: '#E6F8FF',
  turquoise: '#4AD2CA',
  softTurquoise: '#EAFAF9',
  red: '#FF525C',
  magenta: '#E052BD',
  softMagenta: '#FBE9F7',
  purple: '#BF67C7',
  softViolet: '#F0E7FD',
  blueDark: '#001157',
} as const;

const SPECIAL_INVERT: SpecialInvert = {
  blueLight: '#0ABBFB',
  blue: '#3F7DFE',
  blueDeep: '#3E51B5',
  greenLight: '#C0D20F',
  green: '#5ECF70',
  greenDeep: '#44BF78',
  tiffany: '#5BD8D1',
  tiffanyDeep: '#24A79F',
  tiffanyDark: '#147F94',
  tiffanyBlue: '#00BCD4',
  yellow: '#F0DE37',
  orangeLight: '#FFAF37',
  orange: '#FF8515',
  orangeDeep: '#FF5A32',
  violetLight: '#ED6CCD',
  violet: '#C368DA',
  violetDeep: '#9A64F7',
  fuchsia: '#F86D86',
  fuchsiaDeep: '#D9477C',
  rainySky: '#62676F',
  gray: '#98ABCD',
  blueDark: '#001157',
  softBlue: '#E0F2FF',
  softNiceBlue: '#E0E9FF',
  softSkyBlue: '#E2F4FE',
  softTiffany: '#DBF8FF',
  softGreen: '#D8F5E8',
  softYellow: '#FFF1D4',
  softPapaya: '#F9EECF',
  softRed: '#FFEBED',
  softPink: '#FFEBF8',
  softPurple: '#EDF1FF',
  softMallowPurple: '#E8E6FF',
  softGray: '#F1F2F4',
} as const;

export const COLOR: Color = {
  basic: BASIC,
  background: BACKGROUND,
  text: TEXT,
  status: STATUS,
  special: SPECIAL,
  specialInvert: SPECIAL_INVERT,
} as const;
