export const IMAGE_VIEWER_TOOLBAR_HEIGHT = 44;
export const IMAGE_VIEWER_TOOLBAR_PADDING = '2px 12px';
export const IMAGE_VIEWER_TOOLBAR_BORDER_RADIUS = 24;
export const IMAGE_VIEWER_TOOLBAR_BUTTON_SIZE = 40;
export const IMAGE_VIEWER_TOOLBAR_ICON_SIZE = 24;

export const IMAGE_MINIATURE_SIZE_XXS = 40;
export const IMAGE_MINIATURE_SIZE_XS = 56;
export const IMAGE_MINIATURE_SIZE_S = 72;
export const IMAGE_MINIATURE_SIZE_M = 96;
export const IMAGE_MINIATURE_SIZE_L = 128;
export const IMAGE_MINIATURE_SIZE_XL = 192;

export const IMAGE_MINIATURE_ICON_SIZE_XXS_XS = 20;
export const IMAGE_MINIATURE_ICON_SIZE_S_M = 24;
export const IMAGE_MINIATURE_ICON_SIZE_L_XL = 40;
