export const IMAGE_VIEWER_CONTROLS_HEIGHT = 44;
export const IMAGE_VIEWER_CONTROLS_PADDING = '2px 12px';
export const IMAGE_VIEWER_CONTROLS_BORDER_RADIUS = 24;
export const IMAGE_VIEWER_CONTROL_BUTTON_SIZE = 40;
export const IMAGE_VIEWER_CONTROL_ICON_SIZE = 24;
