export type Dimension = 'l' | 'm';

export const TAB_HEIGHT_L = 48;
export const TAB_HEIGHT_M = 40;
export const LINE_HEIGHT = '2px';
export const ICON_SIZE_M = 20;
export const ICON_SIZE_L = 24;
export const TAB_PADDING_M = '0 12px';
export const TAB_PADDING_L = '0 16px';
export const ICON_MARGIN = '8px';
export const BADGE_MARGIN = '8px';
export const OVERFLOW_MENU_CONTAINER_SIZE_M = '40px';
export const OVERFLOW_MENU_CONTAINER_SIZE_L = '48px';
export const OVERFLOW_MENU_MARGIN_M = '10px';
export const OVERFLOW_MENU_MARGIN_L = '12px';
export const FOCUS_BORDER_OFFSET_M = '8px';
export const FOCUS_BORDER_OFFSET_L = '10px';
export const TAB_LEFT_OFFSET_L = -48;
export const TAB_LEFT_OFFSET_M = -40;
