export const ACTION_BAR_ITEM_HEIGHT_XL = 56;
export const ACTION_BAR_ITEM_HEIGHT_L = 48;
export const ACTION_BAR_ITEM_HEIGHT_M = 40;
export const ACTION_BAR_ITEM_HEIGHT_S = 32;

export const DIVIDER_SIZE_M = 20;
export const DIVIDER_SIZE_S = 16;

export const ACTION_BAR_DROP_MENU_ITEM_ICON_SIZE_S = 20;
export const ACTION_BAR_DROP_MENU_ITEM_ICON_SIZE_M = 24;
export const FOCUS_ACTION_BAR_OVERFLOW_MENU_BORDER_OFFSET_XL = 20;
export const FOCUS_ACTION_BAR_OVERFLOW_MENU_BORDER_OFFSET_L = 12;
export const FOCUS_ACTION_BAR_OVERFLOW_MENU_BORDER_OFFSET_M = 10;
export const FOCUS_ACTION_BAR_OVERFLOW_MENU_BORDER_OFFSET_S = 8;
